namespace Nefe.Service.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class _as : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Products", "Category_Id", "dbo.Categories");
            DropForeignKey("dbo.OrderDetails", "Order_Id", "dbo.Orders");
            DropForeignKey("dbo.OrderDetails", "Product_Id", "dbo.Products");
            DropForeignKey("dbo.Orders", "User_Id", "dbo.Users");
            DropForeignKey("dbo.Products", "ProductPackage_Id", "dbo.ProductPackages");
            DropForeignKey("dbo.Addresses", "User_Id", "dbo.Users");
            DropForeignKey("dbo.UserRoles", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles");
            DropIndex("dbo.Addresses", new[] { "User_Id" });
            DropIndex("dbo.Products", new[] { "Category_Id" });
            DropIndex("dbo.Products", new[] { "ProductPackage_Id" });
            DropIndex("dbo.OrderDetails", new[] { "Order_Id" });
            DropIndex("dbo.OrderDetails", new[] { "Product_Id" });
            DropIndex("dbo.Orders", new[] { "User_Id" });
            DropIndex("dbo.UserRoles", new[] { "UserId" });
            DropIndex("dbo.UserRoles", new[] { "RoleId" });
            DropColumn("dbo.OrderDetails", "OrderId");
            DropColumn("dbo.OrderDetails", "ProductId");
            DropColumn("dbo.Orders", "UserId");
            RenameColumn(table: "dbo.Products", name: "Category_Id", newName: "CategoryId");
            RenameColumn(table: "dbo.OrderDetails", name: "Order_Id", newName: "OrderId");
            RenameColumn(table: "dbo.OrderDetails", name: "Product_Id", newName: "ProductId");
            RenameColumn(table: "dbo.Orders", name: "User_Id", newName: "UserId");
            RenameColumn(table: "dbo.Products", name: "ProductPackage_Id", newName: "ProductPackageId");
            DropPrimaryKey("dbo.Addresses");
            DropPrimaryKey("dbo.Categories");
            DropPrimaryKey("dbo.Products");
            DropPrimaryKey("dbo.OrderDetails");
            DropPrimaryKey("dbo.Orders");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Roles");
            DropPrimaryKey("dbo.ProductPackages");
            DropPrimaryKey("dbo.UserRoles");
            AddColumn("dbo.Products", "Descripton", c => c.String(maxLength: 250));
            AlterColumn("dbo.Addresses", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Addresses", "AddressDesc", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.Addresses", "User_Id", c => c.Int());
            AlterColumn("dbo.Categories", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Categories", "Name", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Categories", "Description", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.Products", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Products", "Name", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Products", "UnitPrice", c => c.Decimal(nullable: false, precision: 5, scale: 2));
            AlterColumn("dbo.Products", "Quantity", c => c.Decimal(nullable: false, precision: 4, scale: 2));
            AlterColumn("dbo.Products", "TotalStockAmount", c => c.Decimal(nullable: false, precision: 7, scale: 2));
            AlterColumn("dbo.Products", "SeasonDate", c => c.DateTime());
            AlterColumn("dbo.Products", "CategoryId", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "ProductPackageId", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderDetails", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.OrderDetails", "OrderId", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderDetails", "ProductId", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Orders", "RequiredDate", c => c.DateTime());
            AlterColumn("dbo.Orders", "ShippedDate", c => c.DateTime());
            AlterColumn("dbo.Orders", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Users", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Users", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Users", "LastName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Users", "PhoneNumber", c => c.String(maxLength: 11));
            AlterColumn("dbo.Users", "Email", c => c.String(maxLength: 50));
            AlterColumn("dbo.Users", "Password", c => c.String(maxLength: 50));
            AlterColumn("dbo.Users", "BirthDate", c => c.DateTime());
            AlterColumn("dbo.Roles", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Roles", "RoleName", c => c.String(maxLength: 20, unicode: false));
            AlterColumn("dbo.Roles", "Description", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.ProductPackages", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ProductPackages", "PackageName", c => c.String(maxLength: 100, unicode: false));
            AlterColumn("dbo.UserRoles", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserRoles", "RoleId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Addresses", "Id");
            AddPrimaryKey("dbo.Categories", "Id");
            AddPrimaryKey("dbo.Products", "Id");
            AddPrimaryKey("dbo.OrderDetails", "Id");
            AddPrimaryKey("dbo.Orders", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.Roles", "Id");
            AddPrimaryKey("dbo.ProductPackages", "Id");
            AddPrimaryKey("dbo.UserRoles", new[] { "UserId", "RoleId" });
            CreateIndex("dbo.Addresses", "User_Id");
            CreateIndex("dbo.Products", "CategoryId");
            CreateIndex("dbo.Products", "ProductPackageId");
            CreateIndex("dbo.OrderDetails", "OrderId");
            CreateIndex("dbo.OrderDetails", "ProductId");
            CreateIndex("dbo.Orders", "UserId");
            CreateIndex("dbo.UserRoles", "UserId");
            CreateIndex("dbo.UserRoles", "RoleId");
            AddForeignKey("dbo.Products", "CategoryId", "dbo.Categories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderDetails", "OrderId", "dbo.Orders", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderDetails", "ProductId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "ProductPackageId", "dbo.ProductPackages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Addresses", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.UserRoles", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles", "Id", cascadeDelete: true);
            DropColumn("dbo.Products", "ShortDesc");
            DropColumn("dbo.Products", "LongDesc");
            DropColumn("dbo.OrderDetails", "UnitPrice");
            DropColumn("dbo.OrderDetails", "Quantity");
        }
        
        public override void Down()
        {
            AddColumn("dbo.OrderDetails", "Quantity", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.OrderDetails", "UnitPrice", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "LongDesc", c => c.String());
            AddColumn("dbo.Products", "ShortDesc", c => c.String(maxLength: 50));
            DropForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles");
            DropForeignKey("dbo.UserRoles", "UserId", "dbo.Users");
            DropForeignKey("dbo.Addresses", "User_Id", "dbo.Users");
            DropForeignKey("dbo.Products", "ProductPackageId", "dbo.ProductPackages");
            DropForeignKey("dbo.Orders", "UserId", "dbo.Users");
            DropForeignKey("dbo.OrderDetails", "ProductId", "dbo.Products");
            DropForeignKey("dbo.OrderDetails", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.Products", "CategoryId", "dbo.Categories");
            DropIndex("dbo.UserRoles", new[] { "RoleId" });
            DropIndex("dbo.UserRoles", new[] { "UserId" });
            DropIndex("dbo.Orders", new[] { "UserId" });
            DropIndex("dbo.OrderDetails", new[] { "ProductId" });
            DropIndex("dbo.OrderDetails", new[] { "OrderId" });
            DropIndex("dbo.Products", new[] { "ProductPackageId" });
            DropIndex("dbo.Products", new[] { "CategoryId" });
            DropIndex("dbo.Addresses", new[] { "User_Id" });
            DropPrimaryKey("dbo.UserRoles");
            DropPrimaryKey("dbo.ProductPackages");
            DropPrimaryKey("dbo.Roles");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Orders");
            DropPrimaryKey("dbo.OrderDetails");
            DropPrimaryKey("dbo.Products");
            DropPrimaryKey("dbo.Categories");
            DropPrimaryKey("dbo.Addresses");
            AlterColumn("dbo.UserRoles", "RoleId", c => c.Long(nullable: false));
            AlterColumn("dbo.UserRoles", "UserId", c => c.Long(nullable: false));
            AlterColumn("dbo.ProductPackages", "PackageName", c => c.String());
            AlterColumn("dbo.ProductPackages", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Roles", "Description", c => c.String());
            AlterColumn("dbo.Roles", "RoleName", c => c.String());
            AlterColumn("dbo.Roles", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Users", "BirthDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Users", "Password", c => c.String());
            AlterColumn("dbo.Users", "Email", c => c.String());
            AlterColumn("dbo.Users", "PhoneNumber", c => c.String());
            AlterColumn("dbo.Users", "LastName", c => c.String());
            AlterColumn("dbo.Users", "Name", c => c.String());
            AlterColumn("dbo.Users", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Orders", "UserId", c => c.Long());
            AlterColumn("dbo.Orders", "ShippedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Orders", "RequiredDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Orders", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.OrderDetails", "ProductId", c => c.Long());
            AlterColumn("dbo.OrderDetails", "OrderId", c => c.Long());
            AlterColumn("dbo.OrderDetails", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Products", "ProductPackageId", c => c.Long());
            AlterColumn("dbo.Products", "CategoryId", c => c.Long());
            AlterColumn("dbo.Products", "SeasonDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Products", "TotalStockAmount", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("dbo.Products", "Quantity", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("dbo.Products", "UnitPrice", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("dbo.Products", "Name", c => c.String());
            AlterColumn("dbo.Products", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Categories", "Description", c => c.String());
            AlterColumn("dbo.Categories", "Name", c => c.String());
            AlterColumn("dbo.Categories", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Addresses", "User_Id", c => c.Long());
            AlterColumn("dbo.Addresses", "AddressDesc", c => c.String());
            AlterColumn("dbo.Addresses", "Id", c => c.Long(nullable: false, identity: true));
            DropColumn("dbo.Products", "Descripton");
            AddPrimaryKey("dbo.UserRoles", new[] { "UserId", "RoleId" });
            AddPrimaryKey("dbo.ProductPackages", "Id");
            AddPrimaryKey("dbo.Roles", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.Orders", "Id");
            AddPrimaryKey("dbo.OrderDetails", "Id");
            AddPrimaryKey("dbo.Products", "Id");
            AddPrimaryKey("dbo.Categories", "Id");
            AddPrimaryKey("dbo.Addresses", "Id");
            RenameColumn(table: "dbo.Products", name: "ProductPackageId", newName: "ProductPackage_Id");
            RenameColumn(table: "dbo.Orders", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.OrderDetails", name: "ProductId", newName: "Product_Id");
            RenameColumn(table: "dbo.OrderDetails", name: "OrderId", newName: "Order_Id");
            RenameColumn(table: "dbo.Products", name: "CategoryId", newName: "Category_Id");
            AddColumn("dbo.Orders", "UserId", c => c.Int(nullable: false));
            AddColumn("dbo.OrderDetails", "ProductId", c => c.Int(nullable: false));
            AddColumn("dbo.OrderDetails", "OrderId", c => c.Int(nullable: false));
            CreateIndex("dbo.UserRoles", "RoleId");
            CreateIndex("dbo.UserRoles", "UserId");
            CreateIndex("dbo.Orders", "User_Id");
            CreateIndex("dbo.OrderDetails", "Product_Id");
            CreateIndex("dbo.OrderDetails", "Order_Id");
            CreateIndex("dbo.Products", "ProductPackage_Id");
            CreateIndex("dbo.Products", "Category_Id");
            CreateIndex("dbo.Addresses", "User_Id");
            AddForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserRoles", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Addresses", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Products", "ProductPackage_Id", "dbo.ProductPackages", "Id");
            AddForeignKey("dbo.Orders", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.OrderDetails", "Product_Id", "dbo.Products", "Id");
            AddForeignKey("dbo.OrderDetails", "Order_Id", "dbo.Orders", "Id");
            AddForeignKey("dbo.Products", "Category_Id", "dbo.Categories", "Id");
        }
    }
}
